# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11sYI_gOV7xP6rkTdVsVDAOanWjTV6H76
"""

n = 7;
print(n*n)